### ISSUE TITLE
Schema e  casos de uso

### ISSUE THREAD

**Issue by Murphyly** [Murphyly/mate85_ecommerce#1]

**Comment by Murphyly** [comment]
@andresantosufba preparou um documento mais detalhado dos requisitos, precisa de revisão, está disponível em https://docs.google.com/document/d/1x-Ov1JP3ZGBNA8U6aL3TefckxmE77ywwSIGK5gv9d7E/edit?usp=sharing

**Comment by jompp** [comment]
@Murphyly @andresantosufba 
Fui dar uma revvisada hoje de noite mas não consegui editar o doc. Deixei alguns pontos anotados aqui pra quando liberar o acesso eu comentar no doc. Enquanto estava pensando sobre, aproveitei pra iniciar algumas coisas coisas que vão ser úteis também:

- [ERD](https://drive.google.com/file/d/1KTt-UzrbpSXf8O-Tp2l4GTQSUflH78hm/view?usp=drive_link): Tem quase nada ainda, mas vou melhorando no decorrer do dia pra ver se chegamos à uma versão aceitável pra mostrar pro prof (com mais tabelas e relacionamentos definidos certinho).
- [Fluxograma de Processos](https://lucid.app/lucidchart/c2ce8835-26f7-4a71-a952-a6e6dc677d8d/edit?viewport_loc=58%2C13%2C3003%2C2157%2C0_0&invitationId=inv_b73ef0bf-3b4e-403b-8ee1-ab8a56c1dddf): Maneira fácil de visualizar quais são as possíveis jornadas dentro do nosso sistema. Feito em alto nível pra apenas dar uma ideia mais geral do que nossa aplicacão suporta, mas podemos fazer diagramas mais detalhados sobre o workflow de processos mais complicados.

**Comment by Shirkit** [comment]
Se a gente usar um Auth Provider não precisa guardar `password` no banco, não precisa ainda modelar opções de cartão e pagamento no momento. Endereço são 2 (cobrança e entrega) que é bom distinguir, e já acho que guarda o país lá também.

Produto deveria ter um adicional para se vai ou não controlar o estoque, se o produto está ou disponível para compra (com esses dois você, as fotos do produto (so colocar para resolver depois como elas serão guardadas).

Acho que tá faltando também o conceito de pedido, que deveria ter os produtos do pedido, os preços dos produtos, o valor do frete, qual cliente comprou, e o endereço de entrega e cobrança, o status atual do pedido.

Precisa também guardar a sessão de alguma forma no servidor.

**Comment by Murphyly** [comment]
Gente, desculpa acabei esquecendo de mandar para vocês, o Schema aqui na nossa wiki, qualquer um pode editar @jompp poderia incluir os atributos lá? Acho que as tabelas ficaram bem parecidas. O segundo link que mandou não consegui acessar
@Shirkit dá uma olhadinha acho que consegui colocar a maioria das tabelas, a de guardar a sessão ontem pensei em colocar depois fiquei na dúvida se poderia ser incluído em outra tabela, mas acabei colocando hoje

**Comment by jompp** [comment]
@Shirkit Show, valeu pelas observacões. Sobre a questão dos cartões, a gente não vai dar suporte a pagamentos reais, então, pra simplificar, pensei em fazer uma tabela com as informacões dos cartoes **(fakes, obviamente)** só pra ter a funcionalidade de conseguir salvar um método de pagamento mesmo sem precisar tokenizar e etc. Os conceitos de pedido e várias outras coisas tão faltando ainda, mas vamos adicionando aos poucos. Tentei ser o mais simples e cru possível, desconsiderando qualquer decisão de arquitetura da aplicacao já que isso ta diretamente relacionado às tecnologias, o que a gente ainda não definiu direito... daí depois é só modificar as pequenas coisas que podem varia, como a forma de autenticacão, por exemplo.

@Murphyly Foi mal eu também nem pensei em olhar lá... vou dar uma conferida nisso depois

**Comment by Murphyly** [comment]
[Entregável](https://github.com/Murphyly/mate85_ecommerce/wiki/System-requirements) dessa issue nessa milestone
