### ISSUE TITLE
Listagem de usuários cadastrados

### ISSUE THREAD

**Issue by Murphyly** [Murphyly/mate85_ecommerce#17]

**Comment by Murphyly** [comment]
@Shirkit essa aqui é uma tela válida? Ou o Next auth já gera também?

**Comment by Shirkit** [comment]
Não tinha visto, mas não, não gera. o Next Auth não gera nenhuma tela, só lembrando que eu falei que o processo de adicionar usuário se torna obsoleto devido ao OAuth que iremos usar.

**Comment by Murphyly** [comment]
Listagem de usuários em tabela com botão adicionar e editar
