### ISSUE TITLE
Cadastro de pedido

### ISSUE THREAD

**Issue by Murphyly** [Murphyly/mate85_ecommerce#18]

**Comment by Murphyly** [comment]
@moreirarodrigo @arthurglima 


![Image](https://github.com/Murphyly/mate85_ecommerce/assets/24719642/bc6893f8-58ac-42e9-8f3d-6ddb1774b387)

**Comment by Murphyly** [comment]
- Carrinho - Pedro
- Checkout - Rodrigo e Arthur
- Comprovante de pedido - Julian
- Listagem de pedidos no admin - Rodrigo

**Comment by Murphyly** [comment]
Estrutura de dados do carrinho

let a = {
  cartItems: [
    {
      quantity: "INTEGER",
      product: {
        // "DEFINIÇÃO DO SCHEMA DO PRISMA"
      },
    },
  ],
  cartTotal: "FLOAT",
};

**Comment by moreirarodrigo** [comment]
> * Carrinho - Pedro
> 
>     * Checkout - Rodrigo e Arthur
> 
>     * Comprovante de pedido - Julian
> 
>     * Listagem de pedidos no admin - Rodrigo

Tela de listagem dos pedidos no admin, nessa tela fiz apenas a listagem da tabela orders, queria discutir se é interessante trazer também elementos de address, e product_item ou se é melhor ter um botão que permitisse ver esses detalhes do pedido, o botão edit não está funcional, imagino que em um pedido a única coisa que possa ser alterada seja o status dele

![Screenshot 2023-10-08 at 22-22-49 ShopIC](https://github.com/Murphyly/mate85_ecommerce/assets/55116852/cbc65171-d486-40e6-be63-039e93392643)

Tela de confirmação de pedido (tem um título "Revise seu Pedido" que eu esqueci de incluir antes de tirar a screenshot), os dados são mockados (principalmente o address eu copiei a linha do banco de dados e colei num json), a ídeia é que na aba de resumo seja possível ver além do subtotal e total (que eu sinceramente não sei a diferença, já que nos exemplos que busquei mesmo com múltiplos itens diferentes o subtotal era igual ao total) , desconto, cupom ou algo do gênero, se isso um dia se tornar uma feature, além do método de pagamento selecionado (e no caso de cartão mostrar até quantas parcelas), esqueci de colocar um botão para mudar/adicionar endereço na parte do endereço de entrega, mas também vai ser necessário alterar o schema para que haja um endereço padrão (não fiz alterações nos schemas), mas a ideia é que dê para abrir um pop-up/modal para selecionar outro endereço ou adicionar um novo 

![Screenshot 2023-10-08 at 22-18-58 ShopIC](https://github.com/Murphyly/mate85_ecommerce/assets/55116852/cc110749-365f-4a3f-a937-65042301b1e4)

**Comment by Danub2002** [comment]
como que ta essa issue aqui?

**Comment by Murphyly** [comment]
O que está faltando nessa issue @moreirarodrigo @Shirkit @arthurglima ?

**Comment by Shirkit** [comment]
Essa aqui está vinculada a #42 quando eu terminar fecho essa
