### ISSUE TITLE
Cadastro de usuários

### ISSUE THREAD

**Issue by Murphyly** [Murphyly/mate85_ecommerce#19]

**Comment by Shirkit** [comment]
Acho que com o Next auth e autenticação feita pelo usuário, faz mais sentido o próprio usuário se registrar e depois um administrador ajustar as permissões daquele usuário.

**Comment by Danub2002** [comment]
Eu também acho, era isso que eu tava querendo discutir ontem no grupo

**Comment by Murphyly** [comment]
@glsvitoria está querendo fazer essa parte. Você poderiam fazer uma call rápida para alinhar isso @Shirkit e @Danub2002

**Comment by Shirkit** [comment]
Não precisa fazer essa tela, já que o registro de usuários vai fazer pelo Next Auth no futuro. Uma vez a conta criada, o admin poderá acessar a tela de editar usuário e elevar a permissão daquele usuário. Mais simples e uma tela a menos.

**Comment by Murphyly** [comment]
google por exemplo

**Comment by Shirkit** [comment]
Issue relevante ficou na #34 com a imlpementação
