### ISSUE TITLE
Tela de categórias do tipo de roupas

### ISSUE THREAD

**Issue by Murphyly** [Murphyly/mate85_ecommerce#26]

**Comment by Danub2002** [comment]
Já tem alguem fazendo essa issue?

**Comment by AlexsandreEmanoel** [comment]
Olá Danilo, sim sou eu.

**Comment by Danub2002** [comment]
Já tem algo dessa tela? Posso fazer a sidebar dela

**Comment by AlexsandreEmanoel** [comment]
Danilo, minha branch é develop-alexsandre.. está com erro, pode dar uma olhada também, Isys também está vendo.

**Comment by Danub2002** [comment]
Beleza, vou dar uma olhada nela

**Comment by Danub2002** [comment]
Subi agora um protótipo dessa tela na minha banch (develop-danilo)

**Comment by AlexsandreEmanoel** [comment]
Certo Danilo, amanha vou olhar e tentar terminar a minha.
