### ISSUE TITLE
Página de confirmação de pedido efetuado

### ISSUE THREAD

**Issue by Murphyly** [Murphyly/mate85_ecommerce#29]

**Comment by JulianReina96** [comment]
![image](https://github.com/Murphyly/mate85_ecommerce/assets/87534209/21641fad-e09d-46a1-a136-744eedffa0f9)

Fiz um template básico de uma possível tela para confirmação de pedidos.

**Comment by JulianReina96** [comment]
No momento está estática, seria preciso alinhar com a pagina de finalizar compra pra receber os campos que serão preenchidos.

Nome, e-mail e dados do pedido

**Comment by Shirkit** [comment]
Oi @JulianReina96 porque não usa as informações de um pedido vindo do router? Baseado em um ID de pedido, mostra a confirmação do pedido desse ID. Depois a gente verifica a questão de segurança, já pra tela ficar pronta pro futuro. Só fazer igual ao caminho que temos para o product/[id] só que pra order. Lê as informações do prisma da order e pronto, já renderiza elas na tela.

[https://woocommerce.com/wp-content/uploads/2022/04/blog-Order-Details@2x.jpg](Exemplo de uma imagem pra se basear)

Também precisa mostrar os produtos que foram comprados, as imagens de cada um dos produtos (usa um valor do picsum por enquanto), o valor pago em cada produto e as quantidades.

**Comment by Shirkit** [comment]
Massa, só usar o model do Prisma, mas pelo visto vai ter que adicionar coisas talvez: 
- não temos no momento a data e hora do pedido, acho bom no model ser um DateTime.
- nem a forma do pagamento. Acho que poderia ser uma String que o Gateway (que só colocaremos um dummy que aprova o pagamento na hora) irá colocar.

**Comment by JulianReina96** [comment]
![Print](https://github.com/Murphyly/mate85_ecommerce/assets/87534209/ae465cc3-18c1-408e-83f4-42815e952ef7)


Adicionei as funcionalidades para puxar direto do banco as informações do pedido, mas tive problemas com dois pontos:

Está apresentando erros na renderização (Aparentemente a versao renderizada nao fica igual ao servidor caso eu atualize a pagina)

Não entendi muito bem o fluxo dos parametros. Acredito que será feito atraves de um router, irei verificar e se sim,  será inserido na proxima etapa.

**Comment by Shirkit** [comment]
Sim, o parâmetro do ID do pedido chega através do router. Para isso, você teria que colocar tipo em uma pasta assim `(website)/pedido/[id]/confirmacao/page.jsx` ou `(website)/pedido/confirmacao/[id]/page.jsx` e daí da função que exporta no page.jsx você declara `export default function FUNÇÃO({ params })` para receber o params do Next, e daí você pode acessar o `params.id`.

Se tiver dúvida ou dificildade, pode me falar. Mas veja o exemplo da pasta `(website)/product/[id]/page.jsx` e da documentação do Next aqui: https://nextjs.org/docs/app/building-your-application/routing/dynamic-routes

**Comment by JulianReina96** [comment]
Implementei o parametro pelo id e fiz a inserção das diferenças de acordo com o status do pedido. Dependendo do status, teremos paginas diferentes.


![Captura de tela 2023-09-28 200406](https://github.com/Murphyly/mate85_ecommerce/assets/87534209/244c93f7-6578-4647-98f3-4dcd6b1ca996)
![Captura de tela 2023-09-28 200426](https://github.com/Murphyly/mate85_ecommerce/assets/87534209/d04489be-7691-46e7-ae54-9a9f146858e3)
![Captura de tela 2023-09-28 200450](https://github.com/Murphyly/mate85_ecommerce/assets/87534209/d97fc76e-0783-423e-a631-438824d8e5e2)

Estou usando no momento 3 status presentes no banco. Quando a tabela estiver de fato com dados de pedidos reais, será preciso alinhar se manteremos de fato os 3 status. Pensei em: Confirmado, Pendente e Negado.

E tambem será preciso uma validação para exibir uma mensagem de erro correta, caso o parametro nao corresponda ao id de um pedido no banco.

**Comment by Murphyly** [comment]
Eu acho que essa issue pode ser fechada. Depende de pedido para fechar @JulianReina96 ?

**Comment by JulianReina96** [comment]
Na verdade já foi alterado para exibição de acordo com os status que teremos( são 4). Ideal seria preencher alguns pedidos com os status que de fato usaremos para testar e fechar.
