### ISSUE TITLE
Prototipagem telas

### ISSUE THREAD

**Issue by Murphyly** [Murphyly/mate85_ecommerce#3]

**Comment by glsvitoria** [comment]
Link do protótipo no Figma para visualização:

https://shre.ink/e-commerce-ico045

**Quem quiser ter acesso de edição me manda o email e também precisa ter o figma education, que qualquer estudante da ufba da consegue pedir com o email ufba**

**Comment by jompp** [comment]
Dei uma olhada aqui e tá top man! @glsvitoria 

Eu nem sei como posso ajudar nisso, não manjo nada de design... qualquer coisa que tiver pra me passar só me avisar beleza?

**Comment by glsvitoria** [comment]
Salve @jompp ,

Cara, o que tu pode fazer para me ajudar no protótipo do figma é traduzir os textos para português (Não exatamente igual como é em português, mas uma mescla entre traduzir e algo que caiba no espaço como era em inglês).

Me passa seu email que tenha uma conta no figma, e já pede o figma education nessa [página aqui](https://www.figma.com/education/) para poder editar.

Aí enquanto eu padronizo questão de cor e prototipagem, você vai traduzindo as coisas para mim para eu não perder tempo com isso

**Comment by JulianReina96** [comment]
Tava pensando em tentar prototipar logo uma das telas pra gente conseguir
exibir segunda. Já estamos fechados com esse layout né? Acho que os ajustes
finos(nome da loja, cor) dá pra alterar no código durante a criação tbm.
Alguém começou alguma?

Em qua, 23 de ago de 2023 23:36, Guilherme Lordêlo Seixas Vitória <
***@***.***> escreveu:

**Comment by JulianReina96** [comment]
Galera, tô quase terminando a tradução lá no figma. Salve engano faltam apenas os comentários dos produtos agora.
Aproveitei pra atualizar os preços em Reais e colocar valores em decimais, já que vamos trabalhar com eles no layout.
Quando puderem confiram lá se tá tudo ok. Devo finalizar amanha a tradução dos comentários

**Comment by Murphyly** [comment]
Entregável dessa issue nessa milestone https://shre.ink/e-commerce-ico045
