### ISSUE TITLE
Plano de testes

### ISSUE THREAD

**Issue by Murphyly** [Murphyly/mate85_ecommerce#38]

**Comment by LucaMeireles-ufba** [comment]
Primeira versão do plano de testes criado: https://docs.google.com/document/d/1_r0clZIzcStlFefildKKsXvDuVpjta83SKvnKjyhLog/edit?usp=sharing

**Comment by Shirkit** [comment]
O documento está na Wiki no link: https://github.com/Murphyly/mate85_ecommerce/wiki/Proposta-de-testes
