### ISSUE TITLE
Instalação Ambiente desenvolvimento

### ISSUE THREAD

**Issue by Murphyly** [Murphyly/mate85_ecommerce#5]

**Comment by Murphyly** [comment]
Tenha em mente o [padrão de estrutura](https://nextjs.org/docs/getting-started/project-structure) do projeto para facilitar o entendimento do fluxo de desenvolvimento

**Comment by Shirkit** [comment]
Lembrando que a gente vai usar o "App Router" e que não precisamos definir por agora uma REST API para o frontend chamar. Podemos fazer chamadas diretas ao Backend se o componente for um Server Component e/ou através de [Server Actions](https://nextjs.org/docs/app/building-your-application/data-fetching/forms-and-mutations) dependendo da necessidade.
