### ISSUE TITLE
Arrumar paginação de reviews de um produto

### ISSUE THREAD

**Issue by Murphyly** [Murphyly/mate85_ecommerce#65]
Quando clica para ir para segunda página ele repete alguns itens da primeira página

Rota: /website/produt/[id]

**Comment by Shirkit** [comment]
Só lembrando não faço ideia de como corrigir isso, porque atualmente o ORDER_BY é por rating, teria que ter dois ORDER_BY para ter um por rating e outro por ID para garantir que não misturasse, mas não sei como fazer isso.
Se não der certo isso, talvez o correto seja transformar apenas os reviews em um Client Component e refatorando para remover do `page.js` da vizualização do produto, puxando todas as reviews do banco e aí paginando (na verdade limitando a quantidade de revies mostradas por vez) apenas para não poluir a tela.
