### ISSUE TITLE
Controle de estoque na adição de itens no carrinho pelo usuário

### ISSUE THREAD

**Issue by Murphyly** [Murphyly/mate85_ecommerce#66]
- Mostra notificação está tendo inserir no carrinho um productItem indisponível
- Não deixar adicionar no carrinho quantidade não dispooníveis
- Mostrar quantidade em estoque para cada productItem

**Comment by Shirkit** [comment]
Na vizualização da página de produto, quando o estoque for zero para o ProductItem, ao invés de renderizar zero, deveria mostrar "Fora de Estoque".

**Comment by Shirkit** [comment]
Seguindo o #67 pode tentar também ao zerar a quantidade de itens no carrinho, remover o item do carrinho.

**Comment by Shirkit** [comment]
Talvez deixar o botão de adicionar no carrinho cinza se não tiver estoque, ou então deixar cinza e não clicável a variação (P M ou G) quando não tiver em estoque, sugestão do professor.

**Comment by LucaMeireles-ufba** [comment]
PR criado: https://github.com/Murphyly/mate85_ecommerce/pull/79

Para resolver o problema, quando o usuário seleciona um tamanho que não possui estoque o botão de comprar fica indisponível e muda o texto para "Tamanho indisponível".

A outra solução proposta, para não deixar o botão clicável demonstrou não ser viável pois acarretou outros bugs durante os testes, como mantendo o registro do botão clicado anteriormente e permitindo adicionar ao carrinho sem informar ao usuário qual o tamanho selecionado.

**Comment by Shirkit** [comment]
Massa, e restringiu a quantidade que pode ser adicionada no carrinho? Por exemplo, temos 5 em estoque, e pessoa tenta adicionar 6 ou então 4+4?

**Comment by LucaMeireles-ufba** [comment]
Para esse caso segue o mesmo comportamento anterior. O tratamento feito foi apenas para o caso de produto sem estoque, podemos tratar este comportamento num segundo ticket.
