### ISSUE TITLE
Inclusão e edição de produto

### ISSUE THREAD

**Issue by Murphyly** [Murphyly/mate85_ecommerce#7]

**Comment by JulianReina96** [comment]
Adicionei um possível protótipo para a inserção de produtos no figma. Acho que pode ser utilizado dentro da "parte administrativa". Penso que o escopo pode ser adicionar,(remover e editar produtos).

**Comment by LucaMeireles-ufba** [comment]
Aproveitando os exemplos para criação de novos produtos, o método para atualizar o produto foi implementado na branch: develop-luca em app/product/EditarProduto.js

**Comment by LucaMeireles-ufba** [comment]
Métodos atualizados seguindo os padrões estabelecidos de nomenclatura e commits.

Server Actions criados: 
![image](https://github.com/Murphyly/mate85_ecommerce/assets/113729163/05bc3730-3612-415f-8513-8fc56fcb464f)
![image](https://github.com/Murphyly/mate85_ecommerce/assets/113729163/604f2c65-c777-4464-8776-9e1cb0d3e0c7)

Componentes criados:
![image](https://github.com/Murphyly/mate85_ecommerce/assets/113729163/4a019826-2160-4392-afe3-842a86dc3d44)
![image](https://github.com/Murphyly/mate85_ecommerce/assets/113729163/3fbfc7ce-858c-4cd6-b72d-6c68ae609b08)

**Comment by Murphyly** [comment]
Acredito que eu e @queilahabreu podemos só finalizar de ajustar essa issue em relação ao layout e podemos fechar

**Comment by JulianReina96** [comment]
Isso, é uma boa. Na minha branch tem uma tela que simula a inserção de múltiplos produtos. A questão seria só alinhar com o server action e analisar se fazemos essa inserção no banco em blocos. Por que por produto eu coloquei: nome, cor, categoria, tamanho e valor.

Ai só ver se de fato é dessa forma que estamos pensando para a hora de inserção de novos produtos.

Ai posso seguir com os ajustes dela ou seguir pra outra issue

**Comment by Murphyly** [comment]
Já existe a inclusão e edição teste realizado

**Comment by LucaMeireles-ufba** [comment]
![Image](https://github.com/Murphyly/mate85_ecommerce/assets/113729163/f13ee2be-41aa-4d98-927b-cad6c1d3cb48)

Tela de criação de novo produto

**Comment by LucaMeireles-ufba** [comment]
![Image](https://github.com/Murphyly/mate85_ecommerce/assets/113729163/0401e646-1fcf-4e3a-a1f2-11fcd19d3483)


![Image](https://github.com/Murphyly/mate85_ecommerce/assets/113729163/e09e085c-3c11-4203-9185-e923f73a1375)



![Image](https://github.com/Murphyly/mate85_ecommerce/assets/113729163/bb1805b8-3d00-4982-af99-15238e0ea617)

Código fonte das páginas criadas

**Comment by LucaMeireles-ufba** [comment]
Obs.: É necessário que o ID da categoria inserida exista.
