### ISSUE TITLE
Definir Schema final

### ISSUE THREAD

**Issue by Murphyly** [Murphyly/mate85_ecommerce#9]

**Comment by Murphyly** [comment]
Na nossa wiki tem o modelo do schema que devemos evoluir

**Comment by Murphyly** [comment]
Nosso [Schema](https://github.com/Murphyly/mate85_ecommerce/wiki/Schema) atual, precisamos definir as relações e atributos para conseguir avançar para os CRUDS

**Comment by Shirkit** [comment]
Acho que remove a tabela **managers** e deixa a parte de autenticação para depois (https://nextjs.org/docs/pages/building-your-application/routing/authenticating). Deixa pra depois fazer por **roles** ou então por **permissions** (ou junta os 2, que é o mais comum).

A sessão faz relação com usuário e com o carrinho.

Ficaria assim

 ```mermaid
---
title: SCHEMA - E-commerce G3 - MATE85
---
classDiagram

   class orders {
    +int id
    +int users_id
    +int total
    +int order_number
    +string status
    +string delivery_deadline
    +string delivery_time
   }

   class order_items {
       +int orders_id
       +int products_id
       +float price
   }

   class users {
    +int id
    +string name
    +string email   }

   class products {
    +int id
    +string name
    +String description
    +float price
    +int product_categories_id
    +string sku
   }

   class product_categories{
       +int id
       +string name
   }

   class session {
    +int id
    +int users_id
    +json cart_contents
    -string session_token
   }

   class address {
    +int users_id
    +int orders_id
    +string type
    +string street
    +string number
    +string complement
    +string complement
    +string neighborhood
    +string city
    +string state
    +string country
    +string zip_code
   }

   products --> product_categories
   order_items --|> orders
   order_items --> products
   address --|> users
   address --|> orders
   session --|> users


```

**Comment by JulianReina96** [comment]
Vamos trabalhar com quantidade de produtos? No caso, teremos o conceito de estoque e "produto indisponivel"? Por que se sim, precisariamos ter essa categoria na tabela de produtos, e tambem uma tela para atualizar os produtos existentes(adicionar, remover e atualizar)
